### ISSUE TITLE
Node Search via API for known node returns invalid or empty JSON

### ISSUE THREAD

**Issue by njohnsn** [netdisco/netdisco#732]
## Expected Behavior

API Search for node by MAC address, IP, or hostname, returns switch port node is connected to.

## Current Behavior

Instead, executing API node search URL via python or in Swagger UI returns invalid JSON or empty JSON
`https://earth.its.uiowa.edu/api/v1/search/node?q=ac%3A87%3Aa3%3A1e%3A6e%3A0c&partial=false&deviceports=true&show_vendor=false&archived=false&age_invert=false
`
returns:
```
   can't parse JSON.  Raw result:
   HASH(0x55e8b3b4aef8)
```
or 
`https://earth.its.uiowa.edu/api/v1/search/node?q=ac87a31e6e0c&partial=false&deviceports=true&show_vendor=false&archived=false&age_invert=false`
returns:
`[]`

## Your Environment

* Netdisco version used:  2.45.7
* SNMP::Info version used: 3.70

**Comment by njohnsn** [comment]
Here is some sample python code:
```
import os
from dotenv import load_dotenv
import requests
import json

load_dotenv()

ND_API_USERNAME = os.getenv('ND_API_USERNAME')
ND_API_PASSWORD = os.getenv('ND_API_PASSWORD')

try:
    r = requests.post('https://earth.its.uiowa.edu/login',
                      auth=(ND_API_USERNAME, ND_API_PASSWORD),
                      headers={'Accept': 'application/json'})
except HTTPError as http_err:
    print(f'HTTP error occurred: {http_err}')  # Python 3.6
except Exception as err:
    print(f'Other error occurred: {err}')  # Python 3.6
else:
    print( r.json()['api_key'] )
    # will emit something like: 9d8ff4b68dbedb804c90e9b375eea48a
    api_key = r.json()['api_key']

try:
    r = requests.get('https://earth.its.uiowa.edu/api/v1/search/node',
                     headers={'Accept': 'application/json',
                              'Authorization': api_key},
                     params={'q': 'ac:87:a3:1e:6e:0c',
                             'partial': 'false',
                             'deviceports': 'true',
                             'show_vendor': 'false',
                             'archived': 'false',
                             'age_invert': 'false'})
except HTTPError as http_err:
    print(f'HTTP error occurred: {http_err}')  # Python 3.6
except Exception as err:
    print(f'Other error occurred: {err}')  # Python 3.6
else:
    print('Success full query!')
    # pretty print the JSON stucture
    print(r.text)
    print(json.dumps(r.json(), indent=2, sort_keys=True))
```

And the result:

```
C:\Users\neilj\Documents\repos\nineoneone\venv\Scripts\python.exe C:/Users/neilj/Documents/repos/nineoneone/ndapitest.py
75c824d68d207fa97a7b34c67777eea4
Success full query!
HASH(0x55e8b3bd0c08)

Traceback (most recent call last):
  File "C:/Users/neilj/Documents/repos/nineoneone/ndapitest.py", line 42, in <module>
    print(json.dumps(r.json(), indent=2, sort_keys=True))
  File "C:\Users\neilj\Documents\repos\nineoneone\venv\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\neilj\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\neilj\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\neilj\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

```

**Comment by ollyg** [comment]
Thanks @njohnsn, I can reproduce the error and do see how it's caused. The fix is not easily apparent, though :-(

I will continue looking at it...

**Comment by ollyg** [comment]
fixed in
[master fc4bd4b3] #732 Node Search via API for known node returns invalid or empty JSON
